# Generated by Django 2.1.1 on 2018-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classs',
            name='grade',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
